# Generated by Django 3.1.2 on 2020-12-07 16:26

import bimblog.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, max_length=100, null=True)),
                ('title', models.CharField(blank=True, help_text='Building name', max_length=50, null=True, verbose_name='Title')),
                ('intro', models.CharField(default=bimblog.models.building_default_intro, help_text='Few words to describe this building', max_length=100, verbose_name='Introduction')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('last_updated', models.DateTimeField(editable=False, null=True)),
                ('address', models.CharField(blank=True, help_text='Something like "Rome - Monteverde" is ok', max_length=100, null=True, verbose_name='Address')),
                ('lat', models.FloatField(default=41.8988, verbose_name='Latitude')),
                ('long', models.FloatField(default=12.5451, help_text='Coordinates from Google Maps or https://openstreetmap.org', verbose_name='Longitude')),
                ('zoom', models.FloatField(default=10, help_text='Maximum should be 19', verbose_name='Zoom factor')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ('-date',),
            },
        ),
    ]
