# Generated by Django 3.1.2 on 2020-12-07 17:22

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='fb_image',
            field=filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='uploads/buildings/images/', verbose_name='Image'),
        ),
    ]
