# Generated by Django 3.1.2 on 2020-12-08 12:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0002_auto_20201207_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='zoom',
            field=models.FloatField(default=10, help_text='Maximum should be 21', verbose_name='Zoom factor'),
        ),
        migrations.CreateModel(
            name='BuildingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the building plan', max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=100, null=True)),
                ('elev', models.FloatField(default=0, verbose_name='Elevation in meters')),
                ('file', models.FileField(max_length=200, upload_to='uploads/buildings/plans/dxf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dxf'])], verbose_name='DXF file')),
                ('geometry', models.JSONField(editable=False, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_plan', to='bimblog.building', verbose_name='Building')),
            ],
            options={
                'verbose_name': 'Building plan',
                'verbose_name_plural': 'Building plans',
                'ordering': ('-elev',),
            },
        ),
    ]
