# Generated by Django 3.1.2 on 2020-12-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0002_buildingelement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildingElement',
        ),
    ]
