# Generated by Django 3.1.2 on 2020-12-13 22:27

import bimblog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0003_auto_20201208_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='uploads/buildings/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='buildingplan',
            name='geometry',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='PhotoStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the photo station', max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(editable=False, max_length=100, null=True)),
                ('intro', models.CharField(default=bimblog.models.photo_station_default_intro, max_length=100, verbose_name='Description')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_station', to='bimblog.building', verbose_name='Building')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildingplan_station', to='bimblog.buildingplan', verbose_name='Building plan')),
            ],
            options={
                'verbose_name': 'Photo station',
                'verbose_name_plural': 'Photo stations',
                'ordering': ('build', 'title'),
            },
        ),
    ]
