# Generated by Django 3.1.2 on 2021-01-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0004_buildingplan_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Discipline name', max_length=50, verbose_name='Titolo')),
                ('intro', models.CharField(blank=True, help_text='Few words to describe the discipline', max_length=100, null=True, verbose_name='Introduzione')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'ordering': ('title',),
            },
        ),
    ]
