# Generated by Django 3.1.2 on 2020-12-14 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0004_auto_20201213_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingplan',
            name='refresh',
            field=models.BooleanField(default=True, verbose_name='Refresh geometry'),
        ),
        migrations.AlterField(
            model_name='buildingplan',
            name='file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='uploads/buildings/plans/dxf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dxf'])], verbose_name='DXF file'),
        ),
        migrations.AlterField(
            model_name='buildingplan',
            name='geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
