# Generated by Django 3.1.2 on 2021-01-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0005_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='disciplines',
            field=models.ManyToManyField(blank=True, to='bimblog.Discipline', verbose_name='Only plans belonging to:'),
        ),
        migrations.AddField(
            model_name='buildingplan',
            name='disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_plan', to='bimblog.discipline', verbose_name='Discipline'),
        ),
    ]
