# Generated by Django 3.1.2 on 2021-01-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0006_auto_20210128_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(help_text='Discipline name', max_length=50, verbose_name='Titolo')),
                ('intro', models.CharField(blank=True, help_text='Few words to describe the discipline', max_length=100, null=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='building',
            name='disciplines',
            field=models.ManyToManyField(blank=True, to='bimblog.Discipline', verbose_name='Show only plans belonging to:'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='intro',
            field=models.CharField(blank=True, help_text='Few words to describe the discipline', max_length=100, null=True, verbose_name='Descrizione'),
        ),
    ]
