# Generated by Django 3.1.2 on 2021-01-31 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0007_auto_20210131_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='disciplinesn',
            field=models.ManyToManyField(blank=True, to='bimblog.DisciplineNode', verbose_name='Show only plans belonging to:'),
        ),
        migrations.AddField(
            model_name='buildingplan',
            name='discn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinen_plan', to='bimblog.disciplinenode', verbose_name='Discipline'),
        ),
    ]
