# Generated by Django 3.1.2 on 2021-02-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0008_auto_20210131_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinenode',
            options={'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
        migrations.RemoveField(
            model_name='building',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='buildingplan',
            name='disc',
        ),
    ]
