# Generated by Django 3.1.2 on 2021-02-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0009_auto_20210201_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discipline',
        ),
    ]
