# Generated by Django 3.1.2 on 2021-02-01 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0010_delete_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinenode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bimblog.disciplinenode', verbose_name='Parent discipline'),
        ),
        migrations.AlterField(
            model_name='building',
            name='disciplinesn',
            field=models.ManyToManyField(blank=True, help_text='Show only plans belonging to chosen disciplines', to='bimblog.DisciplineNode', verbose_name='Disciplines'),
        ),
    ]
