# Generated by Django 3.1.2 on 2021-03-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0011_auto_20210201_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingplan',
            name='build',
        ),
        migrations.RemoveField(
            model_name='buildingplan',
            name='discn',
        ),
        migrations.RemoveField(
            model_name='disciplinenode',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='photostation',
            name='build',
        ),
        migrations.RemoveField(
            model_name='photostation',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='stationimage',
            name='stat',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='BuildingPlan',
        ),
        migrations.DeleteModel(
            name='DisciplineNode',
        ),
        migrations.DeleteModel(
            name='PhotoStation',
        ),
        migrations.DeleteModel(
            name='StationImage',
        ),
    ]
